name: Feature Request
description: A new feature or config option you would like to see added
title: "[Enhancement]: "
labels: ["enhancement"]
body:
  - type: input
    id: salis-version
    attributes:
      label: Salis Arcana Version
      description: Which version of Salis Arcana are you using?
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Context
      description: A clear and concise description of why you want the new feature. (E.g. "I'm always frustrated when...")
    validations:
      required: true
  - type: textarea
    id: request
    attributes:
      label: Requested Feature
      description: A clear and concise description of what you want to happen.
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternative Solutions
      description: A clear and concise description of any alternative solutions or features you've considered or tried
    validations:
      required: true
  - type: textarea
    id: more-info
    attributes:
      label: Additional Context
      description: Any other context about the feature request
  - type: markdown
    attributes:
      value: "Thanks for submitting a feature request!"
